name: CI

on:
  push:
    branches:
      - 4.x-pz
  pull_request:
    branches:
      - 4.x-pz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Verify with Maven
        run: |
          ./mvnw --batch-mode verify site
